# -*- coding:utf-8 -*-
#+title:工程代码文件布局约定
#+author:刘尚亮
#+email:liushangliang@xunlei.com

所有文件编码都应该是 utf-8，每个项目工程文件布局如下：

+ bin/

  存放服务的可执行二进制程序。

+ sbin/

  存放服务的控制脚本，如 start.sh, stop.sh, restart.sh 等。

+ conf/

  存放程序的配置文件。

+ libs/

  项目依赖的二进制库。

+ logs/

  存放程序的日志文件。

+ stat/

  项目有关的统计数据。

+ lua/

  如果项目是 nginx+lua 架构，这里了存放对应的 lua 代码，这部分代码应该是从 src 目录下面拷贝过来的。

以上目录一般是生产环境部署的目录架构，下面补充代码仓库中存在的一些目录和文件：

+ docs/

  项目有关的文档说明。

  1. overview/

	 程序整体概览文档，说明程序的用途，对外的域名端口，整体架构，依赖与被依赖的服务。

  2. protocol/

	 服务的交互协议说明，每个请求和响应的协议应该用一个单独的文件进行说明。

	 + server/

	   与其他服务模块交互的协议说明。

	 + client/

	   与客户端交互的协议说明。

  3. dependency/

	 程序依赖，包括运行依赖的第三方程序和被依赖的第三方程序。

  4. configure/

	 程序配置文件字段说明，一些自描述的协议可能在 conf/目录下的配置文件中已经说明，就不需要写在这里了。

  5. environment

	 分别说明测试环境和线上运行环境，比如，部署的机器，文件路径等。

  6. database

	 说明数据库采用的结构，数据表结构，数据字段说明。

+ src/

  存放程序源代码，源代码应该按照模块存放。

+ test/

  程序测试文件目录，包括单元测试和集成测试，但是有些语言，单元测试文件和源码文件放在一起，比如 go。

+ build/

  外编译路径。

+ install/

  打包的发行版存在的路径。

+ CMakeList.txt

  CMake 编译配置，用来编译程序，生成部署程序。
